#!/usr/bin/env python3
"""
OSC Whispers
    oscwhispers

    Written By:
        Shane Hutter


    Description:
        Acts as an OSC Server/Client combo to forward recieved OSC messages onto various OSC servers based on the path of
        the OSC Messsage.
"""

from oscw.config        import Config
from oscw.exceptions    import *
from oscw.osc           import OSCServer

# Testing only imports
from sys    import argv
from time   import sleep


if __name__ == "__main__":
    with Config(
        argv[1]
        ) as conf:
        with OSCServer( conf ) as server:
            while True:
                sleep(1)