#!/usr/bin/env python3
"""
OSC Whispers
    oscwhispers

    Written By:
        Shane Hutter


    Description:
        Acts as an OSC Server/Client combo to forward recieved OSC messages onto various OSC servers based on the path of
        the OSC Messsage.
"""

from oscw.config        import Config
from oscw.exceptions    import *
from oscw.osc           import OSCServer

from time       import sleep
from argparse   import ArgumentParser


def parse_args():
    parser = ArgumentParser( description="Open Sound Control Whispers" )
    parser.add_argument(
        "-c",
        "--config",
        nargs=1,
        default="/etc/oscwhispers.yml",
        help="Location of oscwhispers YAML configuration file",
        )
    return parser.parse_args()

if __name__ == "__main__":
    args = parse_args()
    with Config( 
        args.config[ 0 ] 
        ) as conf:
        with OSCServer( conf ) as server:
            while True:
                sleep(1)